// autogenerated from tomograph.json
// Mon Jul 31 00:15:26 2023

#ifndef _SYNTH_H
#define _SYNTH_H

/* Number of float (32 bit) samples synth can safely generate without
   internal overflow, i.e. max safe value for 2nd arg of synth().
   That arg divided by 2 is the number of interleaved stereo frames generated. */

#define SONG_FRAMES (8 * 11500 * 97)

#ifdef __cplusplus
extern "C" {
#endif

__attribute__((regparm(2))) void synth(float *outbuf, int samples);

#ifdef __cplusplus
}
#endif

#endif /* _SYNTH_H */
